workflows:
  android-workflow:
    name: Android Debug Build
    environment:
      groups:
        - android
    scripts:
      - name: Build Android APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - ah9807076@gmail.com # Your actual email