workflows:
  android-workflow:
    name: Android Debug Build
    environment: {}
    scripts:
      - name: Build Android APK
        script: |
          gradle clean
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - ah9807076@gmail.com # Replace with your actual email