workflows:
  android-workflow:
    name: Android Debug Build
    environment: {}
    scripts:
      - name: Set Gradle Wrapper Permissions
        script: |
          chmod +x gradlew
      - name: Build Android APK
        script: |
          ./gradlew clean
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - ah9807076@gmail.com # Replace with your actual email